In [1]:
from gl0learn.fit import fit
import numpy as np

In [2]:
def generate_independent(n,p,normalize="precision",rng=None):
    assert normalize in {"covariance", "precision"}
    if rng is None:
        rng = np.random
    elif type(rng) == int:
        rng = np.random.RandomState(rng)

    X = rng.randn(n,p)
    Sigma = Theta = np.eye(p)
    if normalize == "covariance":
        return X, Sigma, Theta
    else:
        diag = np.diag(Theta)
        X *= np.sqrt(diag)
        Sigma = Sigma*np.sqrt(diag)*np.sqrt(diag[:,None])
        Theta = Theta/np.sqrt(diag)/np.sqrt(diag[:,None])
    return X, Sigma, Theta

In [25]:
X, sigma, theta = generate_independent(10, 50)

In [26]:
theta

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [30]:
f = fit(X, l0=0.5, initial_active_set=0.1, super_active_set=0., algorithm="CDPSI")

ap for (5, 13) 
No swap for (5, 18) 
No swap for (5, 21) 
No swap for (5, 22) 
No swap for (5, 28) 
No swap for (5, 41) 
No swap for (5, 45) 
No swap for (5, 46) 
PSI iter: 1 Swapping row: 6
psi_row_fit 
No swap for (6, 13) 
No swap for (6, 18) 
No swap for (6, 21) 
No swap for (6, 27) 
No swap for (6, 32) 
No swap for (6, 33) 
No swap for (6, 34) 
No swap for (6, 40) 
No swap for (6, 48) 
No swap for (6, 49) 
PSI iter: 1 Swapping row: 7
psi_row_fit 
No swap for (7, 12) 
No swap for (7, 14) 
No swap for (7, 21) 
No swap for (7, 23) 
No swap for (7, 26) 
No swap for (7, 28) 
No swap for (7, 36) 
No swap for (7, 37) 
No swap for (7, 45) 
PSI iter: 1 Swapping row: 8
psi_row_fit 
No swap for (8, 4) 
No swap for (8, 10) 
No swap for (8, 16) 
No swap for (8, 21) 
No swap for (8, 25) 
No swap for (8, 26) 
No swap for (8, 30) 
No swap for (8, 31) 
No swap for (8, 34) 
No swap for (8, 36) 
No swap for (8, 43) 
No swap for (8, 45) 
PSI iter: 1 Swapping row: 9
psi_row_fit 
No swap for (9, 3) 
No 

In [31]:
f.active_set_size

[885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 885,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127,
 127

In [32]:
f.theta

array([[20.20866304,  0.        ,  0.        , ..., -0.        ,
         6.06207754,  0.        ],
       [ 0.        , 17.64893629,  0.        , ...,  0.        ,
         0.        , -0.        ],
       [ 0.        ,  0.        , 13.61569052, ...,  0.        ,
         0.        , -0.        ],
       ...,
       [-0.        ,  0.        ,  0.        , ...,  9.07473584,
         0.        ,  0.        ],
       [ 6.06207754,  0.        ,  0.        , ...,  0.        ,
        10.82465983,  0.        ],
       [ 0.        , -0.        , -0.        , ...,  0.        ,
         0.        , 11.26470376]])

In [4]:
np.broadcast_shapes([])

()

In [5]:
args = [np.array(_m, copy=False, subok=False) for _m in [x1, x2]]

In [6]:
args

[array(1),
 array([[1., 1.],
        [1., 1.]])]

In [7]:
np.broadcast_shapes(*args)

TypeError: only integer scalar arrays can be converted to a scalar index

In [13]:
y1, y2 = utils.broadcast_arrays(x1, x2, order="F")

In [14]:
y1.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True  (with WARN_ON_WRITE=True)
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [15]:
y2.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False